# Use the nf-core Gitpod image located at https://github.com/nf-core/tools/blob/master/nf_core/gitpod/gitpod.Dockerfile
image: nfcore/gitpod:latest

# Gitpod definition file adapted from:
#  - https://github.com/nf-core/tools/blob/master/nf_core/pipeline-template/.gitpod.yml
#  - https://github.com/nextflow-io/training/blob/master/.gitpod.yml

tasks:
  # Update Nextflow if image version is behind
  # Install tools for exercises
  - name: Update tools for exercises
    command: |
      conda install --yes --update-all \
        salmon=1.5 \
        fastqc=0.11 \
        multiqc \
      && conda clean --all --force-pkgs-dirs --yes \
      && nextflow self-update \
      && exit
  # Open Carpentries training material in a side panel.
  - name: Open training material
    command: gp preview https://carpentries-incubator.github.io/workflows-nextflow/ && exit
  # Sets up a terminal in the correct location.
  # This must be the last task in the list
  - name: Terminal for training exercises
    command: |
      unset JAVA_TOOL_OPTIONS
      mkdir -p nf-training  # Create the directory
      cd nf-training        # Change into the directory

vscode:
  extensions: # based on nf-core.nf-core-extensionpack
    - codezombiech.gitignore # Language support for .gitignore files
    - cssho.vscode-svgviewer # SVG viewer
    - esbenp.prettier-vscode # Markdown/CommonMark linting and style checking for Visual Studio Code
    - EditorConfig.EditorConfig # override user/workspace settings with settings found in .editorconfig files
    - Gruntfuggly.todo-tree # Display TODO and FIXME in a tree view in the activity bar
    # - mechatroner.rainbow-csv # Highlight columns in csv files in different colors
    - nextflow.nextflow # Nextflow syntax highlighting
    - oderwat.indent-rainbow # Highlight indentation level
    - streetsidesoftware.code-spell-checker # Spelling checker for source code
    - ms-vscode.live-server
